---
title: "Code Design"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CodeDesign}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

It's nice to know how the code works. Let's keep a diary of sorts as we work on this.

Within the simulation loop, we'll want to have process functions for each stage where individuals can become vaccinated. It might look like this:

```
while (run sim)
    vaccination_process()
    infection_process()
    events()
    updates()
end
```

Most of the simulation updates state by TargetedEvents. When a targeted event fires, there are 2 types of listeners that would normally be called.

  1. schedulers - these are functions like `create_event_scheduler_listener` which schedule future events (`create_progression_listener` in original code).
  2. state updates - these are functions like `create_state_update_listener` which update state when the event fires (`create_infection_update_listener` in original code).

There could be others, to update tracking variables for example, but only these two types are necessary for the model dynamics.