# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title C++ infection process (squire model)
#' @description this is an internal function, you should use the R interface
#' for type checking, \code{\link{infection_process_cpp}}
#' @param parameters a list of parameters from \code{\link{get_parameters}}
#' @param states a \code{\link[individual]{CategoricalVariable}}
#' @param discrete_age a \code{\link[individual]{IntegerVariable}}
#' @param exposure a \code{\link[individual]{TargetedEvent}}
#' @param dt size of time step
infection_process_cpp_internal <- function(parameters, states, discrete_age, exposure, dt) {
    .Call('_safir_infection_process_cpp_internal', PACKAGE = 'safir', parameters, states, discrete_age, exposure, dt)
}

#' @title Cross tabulate two vectors with given margins
#' @description this is a replacement for \code{\link[base]{table}} that allows empty
#' cells because the margins have been specified. The input vectors \code{a} and \code{b}
#' must be the same length, this function does no argument checking.
#' @param a one set of observations
#' @param b another set of observations
#' @param a_margin number of distinct values of a (rows)
#' @param b_margin number of distinct values of b (cols)
#' @examples
#' a <- 1:5
#' b <- c(1,2,3,1,2)
#' cross_tab_margins(a,b,5,3)
#' table(a,b)
#' @export
cross_tab_margins <- function(a, b, a_margin, b_margin) {
    .Call('_safir_cross_tab_margins', PACKAGE = 'safir', a, b, a_margin, b_margin)
}

#' @title Tabulate a vector of observations
#' @description Tabulate a vector \code{a} whose values fall into a set of integers
#' of maximum value \code{nbins}. This function does no argument checking so please
#' ensure the maximum value of observations is not greater than \code{nbins}.
#' @param a a set of observations
#' @param nbins number of bins
#' @examples
#' nbin <- 10
#' a <- sample.int(n = nbin,size = 100,replace = T)
#' tabulate(bin = a,nbins = nbin)
#' tab_bins(a = a,nbins = nbin)
#' @export
tab_bins <- function(a, nbins) {
    .Call('_safir_tab_bins', PACKAGE = 'safir', a, nbins)
}

#' @title Get contact matrix
#' @description Get the contact matrix at some specific day (1st dimension of array).
#' @param array the mixing matrix array (days x age x age)
#' @param i the day (indexes the first dimension, assumes zero indexing)
#' @export
get_contact_matrix_cpp <- function(array, i) {
    .Call('_safir_get_contact_matrix_cpp', PACKAGE = 'safir', array, i)
}

#' @title Get a beta value
#' @description Get a beta value at some specific day
#' @param beta_set the set of beta values
#' @param i the day (assumes zero indexing)
#' @export
get_beta_cpp <- function(beta_set, i) {
    .Call('_safir_get_beta_cpp', PACKAGE = 'safir', beta_set, i)
}

#' @title Multiply a matrix by a integer vector
#' @param m a matrix
#' @param a a vector (must have length equal to number of columns of \code{m})
#' @export
matrix_vec_mult_cpp <- function(m, a) {
    .Call('_safir_matrix_vec_mult_cpp', PACKAGE = 'safir', m, a)
}

#' @title Multiply a matrix by a integer vector and a double vector
#' @param m a matrix
#' @param a a vector of int (must have length equal to number of columns of \code{m})
#' @param b a vector of double (must have length equal to number of columns of \code{m})
#' @export
matrix_2vec_mult_cpp <- function(m, a, b) {
    .Call('_safir_matrix_2vec_mult_cpp', PACKAGE = 'safir', m, a, b)
}

