# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Cross tabulate two vectors with given margins
#' @description this is a replacement for \code{\link[base]{table}} that allows empty
#' cells because the margins have been specified. The input vectors \code{a} and \code{b}
#' must be the same length, this function does no argument checking.
#' @param a one set of observations
#' @param b another set of observations
#' @param a_margin number of distinct values of a (rows)
#' @param b_margin number of distinct values of b (cols)
#' @examples
#' a <- 1:5
#' b <- c(1,2,3,1,2)
#' cross_tab_margins(a,b,5,3)
#' table(a,b)
#' @export
cross_tab_margins <- function(a, b, a_margin, b_margin) {
    .Call('_safir_cross_tab_margins', PACKAGE = 'safir', a, b, a_margin, b_margin)
}

